#!/bin/sh

fswait () {
	if command -v inotifywait >/dev/null 2>&1; then
		inotifywait -r -e modify,attrib,close_write ./
	else
		if command -v fswatch >/dev/null 2>&1; then
			fswatch -r -1 ./
		else
			sleep 2;
		fi
	fi
}

syncfiles () {
	rsync -avhe ssh ./ dev.dilewe.de:/var/www/html/dilewe.de/hessen-mediathek/web/wp-content/themes/systemw/
	if [ $? -ne 0 ]; then
		exit
	fi
}

syncfiles
while true; do
	fswait
	syncfiles
done
